# -*- coding: utf-8 -*-
"""tradutor_de_urls.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JzW_eydjN-LaV_Ixe4MMZmoJ9DfJbNFI
"""

!pip install requests beautifulsoup4 openai langchain-openai

import requests
from bs4 import BeautifulSoup

def extract_text_from_url(url):
    try:
        response = requests.get(url)
        response.raise_for_status()
        soup = BeautifulSoup(response.text, 'html.parser')
        for script_or_style in soup(['script', 'style']):
            script_or_style.decompose()
        text = soup.get_text(separator=' ')

        #limpa texto
        lines = (line.strip() for line in text.splitlines())
        parts = (phrase.strip() for line in lines for phrase in line.split("  "))
        clean_text = '\n'.join(part for part in parts if part)
        text = clean_text
    except requests.exceptions.RequestException as e:
        # Catch any exception from requests (ConnectionError, HTTPError, Timeout, etc.)
        text = f"Failed to fetch URL {url}. Error: {e}"
        print(text)
    return text


extract_text_from_url('https://www.terra.com.br/')

from langchain_openai.chat_models.azure import AzureChatOpenAI

client = AzureChatOpenAI(
    azure_endpoint = 'https://openai-dio-tradutor.openai.azure.com/',
    api_key = 'xxxxxxxx',
    api_version="2024-12-01-preview",
    deployment_name="gpt-4.1-mini",
    max_retries=0
)

def translate_page(text, lang):
  messages = [
      ("system", "Você é um tradutor de textos"),
      ("human", f"Traduza o {text} para o idioma {lang} e responda em markdow")
  ]
  response = client.invoke(messages)
  print(response.content)
  return response.content

translate_page("AI offers numerous benefits across various industries and applications. Some of the most commonly cited benefits include:", "portugues")

url = 'https://www.ibm.com/think/topics/artificial-intelligence'
text = extract_text_from_url(url)
article = translate_page(text, 'pt-br')
print(article)